lane :alpha do
  # Adjust the `build_type` and `flavor` params as needed to build the right APK for your setup
  gradle(task: "clean")
  gradle(
    task: 'bundle',
    build_type: 'Release'
  )
  upload_to_play_store(track: 'alpha')
end