lane :alpha do
  gradle(task: "clean")
  increment_version_code(
    gradle_file_path: "app/build.gradle",
  )
  gradle(
    task: 'bundle',
    build_type: 'Release'
  )
  upload_to_play_store(track: 'alpha')
end