name: Code-style

on:
  push:
    branches: [gh-actions]
  pull_request:
    branches: [gh-actions]

jobs:
  lint-and-ts-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: lint-and-ts-check
        run: yarn && yarn validate