name: Code style

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  lint-and-ts-check:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: lint-and-ts-check
        run: yarn && yarn validate